language: node_js
node_js:
- '0.12'
branches:
  only:
  - master

env:
  global:
  - secure: iVvuhPQuwZWkWJCum1kQk+cj4O/qEcwOaO0gMjpPudmAhHx3cJY3y5OAWZ40DaESFEPjLTPhqVbmDAvrz2Cuqd6GnNcbiMdXz70pqtPnKceSD1YJWkmrYQClNgrI/u+4EmC3/OoNnhD/V/kyS2YTaaUC/QdXOkTnst7Mybm6Tlk=
  - secure: WZg+QI6a2dy6afRjeRypsIaXLiKueizEY/mRgRzjbqwRQSBttHdCVR2Hdba7R59myJBzsKLVceHD3nbEKVUc/eYo+oQtQsL/t44rq3HeGYoGt1qq87qk03GsA0/X7600NA1tenDkk7TtAy2RVBa7vHtanHMfpcgogIFXfKqqsqU=

install:
- npm install -g bower
- npm install -g gulp
- npm install -g karma
- npm install -g protractor
- bower install
- npm install
- npm run build

before_script:
- psql -U postgres -a -f ./schema/DDL.sql
- npm start &
- sleep 5

after_script: 
- process.exit()